variables:
  # O nome da conexão que você criou nas 'Service Connections' do Azure DevOps
  azureServiceConnection: 'gabri3lmarques' 
  
  # O Login Server do seu registro
  containerRegistry: 'stockmasterreg.azurecr.io'
  
  backendImage: 'stockmaster-api'
  frontendImage: 'stockmaster-web'