trigger:
- main

# ISSO AQUI Ã‰ O SEGREDO:
pool:
  name: 'Default' 

steps:
- task: Docker@2
  displayName: 'Construindo Backend'
  inputs:
    containerRegistry: 'AcessoAoRegistro'
    repository: 'stockmaster-api'
    command: 'buildAndPush'
    Dockerfile: 'backend/StockMaster.Api/Dockerfile'
    tags: 'latest'

- task: Docker@2
  displayName: 'Construindo Frontend'
  inputs:
    containerRegistry: 'AcessoAoRegistro'
    repository: 'stockmaster-web'
    command: 'buildAndPush'
    Dockerfile: 'frontend/Dockerfile'
    tags: 'latest'