trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # CONFIRME SE ESTE É O NOME DA SUA CONEXÃO
  azureServiceConnection: 'gabri3lmarques' 
  
  # SEU LOGIN SERVER DO PORTAL AZURE
  containerRegistry: 'stockmasterreg.azurecr.io'
  
  backendImage: 'stockmaster-api'
  frontendImage: 'stockmaster-web'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Stage'
  jobs:
  - job: DockerBuild
    displayName: 'Docker Build and Push Job'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Backend'
      inputs:
        containerRegistry: $(azureServiceConnection)
        repository: $(backendImage)
        command: 'buildAndPush'
        Dockerfile: 'backend/StockMaster.Api/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Build and Push Frontend'
      inputs:
        containerRegistry: $(azureServiceConnection)
        repository: $(frontendImage)
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest